// <auto-generated />
using System;
using System.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace System.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261004030517_CriarTabelas")]
    partial class CriarTabelas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("System.Api.Models.CondutorAutorizado", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CnhNumero")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("cnh_numero")
                        .IsFixedLength();

                    b.Property<DateOnly?>("CnhValidade")
                        .HasColumnType("date")
                        .HasColumnName("cnh_validade");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("Parentesco")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("parentesco");

                    b.Property<short>("Posicao")
                        .HasColumnType("smallint")
                        .HasColumnName("posicao");

                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint")
                        .HasColumnName("processo_id");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_condutor_autorizado");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_condutor_autorizado_usuario_id");

                    b.HasIndex("ProcessoId", "Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_condutor_autorizado_processo_id_cpf");

                    b.HasIndex("ProcessoId", "Posicao")
                        .IsUnique()
                        .HasDatabaseName("ix_condutor_autorizado_processo_id_posicao");

                    b.ToTable("condutor_autorizado", null, t =>
                        {
                            t.HasCheckConstraint("ck_condutor_autorizado_parentesco", "parentesco IN ('FATHER', 'MOTHER', 'SPOUSE', 'SIBLING', 'CHILD', 'OTHER')");

                            t.HasCheckConstraint("ck_condutor_autorizado_posicao", "posicao BETWEEN 1 AND 3");
                        });
                });

            modelBuilder.Entity("System.Api.Models.Documento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<long?>("CondutorAutorizadoId")
                        .HasColumnType("bigint")
                        .HasColumnName("condutor_autorizado_id");

                    b.Property<DateOnly?>("DataEmissao")
                        .HasColumnType("date")
                        .HasColumnName("data_emissao");

                    b.Property<DateOnly?>("DataValidade")
                        .HasColumnType("date")
                        .HasColumnName("data_validade");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original");

                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint")
                        .HasColumnName("processo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("status");

                    b.Property<int>("TamanhoBytes")
                        .HasColumnType("integer")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("TipoConteudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_conteudo");

                    b.Property<short>("TipoDocumentoId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("Id")
                        .HasName("pk_documento");

                    b.HasIndex("CondutorAutorizadoId")
                        .HasDatabaseName("ix_documento_condutor_autorizado_id");

                    b.HasIndex("ProcessoId")
                        .HasDatabaseName("ix_documento_processo_id");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("ix_documento_tipo_documento_id");

                    b.ToTable("documento", null, t =>
                        {
                            t.HasCheckConstraint("ck_documento_data", "data_emissao IS NOT NULL OR data_validade IS NOT NULL");

                            t.HasCheckConstraint("ck_documento_status", "status IN ('PENDING', 'VALID', 'EXPIRED', 'REJECTED')");

                            t.HasCheckConstraint("ck_documento_tamanho_bytes", "tamanho_bytes <= 10485760");

                            t.HasCheckConstraint("ck_documento_tipo_conteudo", "tipo_conteudo IN ('application/pdf', 'image/jpeg', 'image/png')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.Dossie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CaminhoArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("caminho_arquivo");

                    b.Property<DateTime>("GeradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("gerado_em");

                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint")
                        .HasColumnName("processo_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<int>("TotalDocumentos")
                        .HasColumnType("integer")
                        .HasColumnName("total_documentos");

                    b.HasKey("Id")
                        .HasName("pk_dossie");

                    b.HasIndex("ProcessoId")
                        .IsUnique()
                        .HasDatabaseName("ix_dossie_processo_id");

                    b.ToTable("dossie", null, t =>
                        {
                            t.HasCheckConstraint("ck_dossie_status", "status IN ('GENERATED')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.Etapa", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("ExplicacaoSimplificada")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("explicacao_simplificada");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.Property<string>("Orgao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("orgao");

                    b.Property<string>("TipoPerfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_perfil");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_etapa");

                    b.HasIndex("TipoPerfil", "Ordem")
                        .IsUnique()
                        .HasDatabaseName("ix_etapa_tipo_perfil_ordem");

                    b.ToTable("etapa", null, t =>
                        {
                            t.HasCheckConstraint("ck_etapa_orgao", "orgao IN ('CLINIC', 'DETRAN', 'RECEITA_FEDERAL', 'SEFAZ', 'DEALERSHIP')");

                            t.HasCheckConstraint("ck_etapa_tipo_perfil", "tipo_perfil IN ('PCD_DRIVER', 'PCD_NON_DRIVER')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.EtapaAcao", b =>
                {
                    b.Property<short>("EtapaId")
                        .HasColumnType("smallint")
                        .HasColumnName("etapa_id");

                    b.Property<short>("Ordem")
                        .HasColumnType("smallint")
                        .HasColumnName("ordem");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.HasKey("EtapaId", "Ordem")
                        .HasName("pk_etapa_acao");

                    b.ToTable("etapa_acao", (string)null);
                });

            modelBuilder.Entity("System.Api.Models.EtapaDocumento", b =>
                {
                    b.Property<short>("EtapaId")
                        .HasColumnType("smallint")
                        .HasColumnName("etapa_id");

                    b.Property<short>("TipoDocumentoId")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_documento_id");

                    b.HasKey("EtapaId", "TipoDocumentoId")
                        .HasName("pk_etapa_documento");

                    b.HasIndex("TipoDocumentoId")
                        .HasDatabaseName("ix_etapa_documento_tipo_documento_id");

                    b.ToTable("etapa_documento", (string)null);
                });

            modelBuilder.Entity("System.Api.Models.Processo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AceiteZeroKmEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("aceite_zero_km_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("CnhNumero")
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("cnh_numero")
                        .IsFixedLength();

                    b.Property<bool?>("CnhPossuiRestricao")
                        .HasColumnType("boolean")
                        .HasColumnName("cnh_possui_restricao");

                    b.Property<DateOnly?>("CnhValidade")
                        .HasColumnType("date")
                        .HasColumnName("cnh_validade");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluido_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataPrevistaCompra")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista_compra");

                    b.Property<DateOnly?>("DataUltimaCompraIsenta")
                        .HasColumnType("date")
                        .HasColumnName("data_ultima_compra_isenta");

                    b.Property<long?>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<string>("TipoDeficiencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_deficiencia");

                    b.Property<string>("TipoPerfil")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_perfil");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<string>("VeiculoModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("veiculo_modelo");

                    b.Property<decimal?>("VeiculoValor")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("veiculo_valor");

                    b.HasKey("Id")
                        .HasName("pk_processo");

                    b.HasIndex("QuizId")
                        .IsUnique()
                        .HasDatabaseName("ix_processo_quiz_id");

                    b.HasIndex("UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_processo_usuario_id")
                        .HasFilter("status <> 'COMPLETED'");

                    b.ToTable("processo", null, t =>
                        {
                            t.HasCheckConstraint("ck_processo_cnh", "tipo_perfil = 'PCD_DRIVER' OR (cnh_numero IS NULL AND cnh_validade IS NULL AND cnh_possui_restricao IS NULL)");

                            t.HasCheckConstraint("ck_processo_status", "status IN ('DRAFT', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED')");

                            t.HasCheckConstraint("ck_processo_tipo_deficiencia", "tipo_deficiencia IN ('PHYSICAL', 'VISUAL', 'HEARING', 'INTELLECTUAL', 'AUTISM', 'DOWN_SYNDROME')");

                            t.HasCheckConstraint("ck_processo_tipo_perfil", "tipo_perfil IN ('PCD_DRIVER', 'PCD_NON_DRIVER')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.ProcessoEtapa", b =>
                {
                    b.Property<long>("ProcessoId")
                        .HasColumnType("bigint")
                        .HasColumnName("processo_id");

                    b.Property<short>("EtapaId")
                        .HasColumnType("smallint")
                        .HasColumnName("etapa_id");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.Property<DateTime?>("ValidadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validada_em");

                    b.HasKey("ProcessoId", "EtapaId")
                        .HasName("pk_processo_etapa");

                    b.HasIndex("EtapaId")
                        .HasDatabaseName("ix_processo_etapa_etapa_id");

                    b.ToTable("processo_etapa", null, t =>
                        {
                            t.HasCheckConstraint("ck_processo_etapa_status", "status IN ('LOCKED', 'IN_PROGRESS', 'VALIDATED')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.Quiz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ConsentimentoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consentimento_em");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool?>("Elegivel")
                        .HasColumnType("boolean")
                        .HasColumnName("elegivel");

                    b.Property<string>("TipoDeficiencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_deficiencia");

                    b.Property<string>("TipoPerfil")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_perfil");

                    b.Property<Guid>("TokenAnonimo")
                        .HasColumnType("uuid")
                        .HasColumnName("token_anonimo");

                    b.Property<long?>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime?>("VinculadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("vinculado_em");

                    b.HasKey("Id")
                        .HasName("pk_quiz");

                    b.HasIndex("TokenAnonimo")
                        .IsUnique()
                        .HasDatabaseName("ix_quiz_token_anonimo");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_quiz_usuario_id");

                    b.ToTable("quiz", null, t =>
                        {
                            t.HasCheckConstraint("ck_quiz_tipo_deficiencia", "tipo_deficiencia IN ('PHYSICAL', 'VISUAL', 'HEARING', 'INTELLECTUAL', 'AUTISM', 'DOWN_SYNDROME')");

                            t.HasCheckConstraint("ck_quiz_tipo_perfil", "tipo_perfil IN ('PCD_DRIVER', 'PCD_NON_DRIVER')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.QuizResposta", b =>
                {
                    b.Property<long>("QuizId")
                        .HasColumnType("bigint")
                        .HasColumnName("quiz_id");

                    b.Property<string>("CodigoPergunta")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_pergunta");

                    b.Property<string>("Resposta")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resposta");

                    b.HasKey("QuizId", "CodigoPergunta")
                        .HasName("pk_quiz_resposta");

                    b.ToTable("quiz_resposta", (string)null);
                });

            modelBuilder.Entity("System.Api.Models.TipoDocumento", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("Dono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dono");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("RegraValidade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("regra_validade");

                    b.Property<int?>("ValidadeDias")
                        .HasColumnType("integer")
                        .HasColumnName("validade_dias");

                    b.HasKey("Id")
                        .HasName("pk_tipo_documento");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_documento_codigo");

                    b.ToTable("tipo_documento", null, t =>
                        {
                            t.HasCheckConstraint("ck_tipo_documento_dono", "dono IN ('HOLDER', 'DRIVER')");

                            t.HasCheckConstraint("ck_tipo_documento_regra_validade", "regra_validade IN ('DAYS_FROM_ISSUE', 'PRINTED_EXPIRY', 'NONE')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.TokenRedefinicaoSenha", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_hash");

                    b.Property<DateTime?>("UsadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("usado_em");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_token_redefinicao_senha");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_token_redefinicao_senha_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_token_redefinicao_senha_usuario_id");

                    b.ToTable("token_redefinicao_senha", (string)null);
                });

            modelBuilder.Entity("System.Api.Models.TokenRevogado", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("jti");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.HasKey("Jti")
                        .HasName("pk_token_revogado");

                    b.ToTable("token_revogado", (string)null);
                });

            modelBuilder.Entity("System.Api.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("AnonimizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonimizado_em");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Bairro")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .HasColumnName("cep")
                        .IsFixedLength();

                    b.Property<string>("Cidade")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("complemento");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .HasColumnName("cpf")
                        .IsFixedLength();

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("logradouro");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_completo");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Papel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("papel");

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("senha_hash");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefone");

                    b.Property<string>("Uf")
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .HasColumnName("uf")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_cpf");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.ToTable("usuario", null, t =>
                        {
                            t.HasCheckConstraint("ck_usuario_papel", "papel IN ('USER', 'ADMIN')");
                        });
                });

            modelBuilder.Entity("System.Api.Models.CondutorAutorizado", b =>
                {
                    b.HasOne("System.Api.Models.Processo", "Processo")
                        .WithMany("Condutores")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_condutor_autorizado_processo_processo_id");

                    b.HasOne("System.Api.Models.Usuario", "Usuario")
                        .WithMany("Conducoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_condutor_autorizado_usuario_usuario_id");

                    b.Navigation("Processo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("System.Api.Models.Documento", b =>
                {
                    b.HasOne("System.Api.Models.CondutorAutorizado", "CondutorAutorizado")
                        .WithMany("Documentos")
                        .HasForeignKey("CondutorAutorizadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documento_condutor_autorizado_condutor_autorizado_id");

                    b.HasOne("System.Api.Models.Processo", "Processo")
                        .WithMany("Documentos")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_documento_processo_processo_id");

                    b.HasOne("System.Api.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documento_tipo_documento_tipo_documento_id");

                    b.Navigation("CondutorAutorizado");

                    b.Navigation("Processo");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("System.Api.Models.Dossie", b =>
                {
                    b.HasOne("System.Api.Models.Processo", "Processo")
                        .WithOne("Dossie")
                        .HasForeignKey("System.Api.Models.Dossie", "ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dossie_processo_processo_id");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("System.Api.Models.EtapaAcao", b =>
                {
                    b.HasOne("System.Api.Models.Etapa", "Etapa")
                        .WithMany("Acoes")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etapa_acao_etapa_etapa_id");

                    b.Navigation("Etapa");
                });

            modelBuilder.Entity("System.Api.Models.EtapaDocumento", b =>
                {
                    b.HasOne("System.Api.Models.Etapa", "Etapa")
                        .WithMany("DocumentosExigidos")
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_etapa_documento_etapa_etapa_id");

                    b.HasOne("System.Api.Models.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_etapa_documento_tipo_documento_tipo_documento_id");

                    b.Navigation("Etapa");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("System.Api.Models.Processo", b =>
                {
                    b.HasOne("System.Api.Models.Quiz", "Quiz")
                        .WithOne("Processo")
                        .HasForeignKey("System.Api.Models.Processo", "QuizId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_processo_quiz_quiz_id");

                    b.HasOne("System.Api.Models.Usuario", "Usuario")
                        .WithMany("Processos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_processo_usuario_usuario_id");

                    b.Navigation("Quiz");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("System.Api.Models.ProcessoEtapa", b =>
                {
                    b.HasOne("System.Api.Models.Etapa", "Etapa")
                        .WithMany()
                        .HasForeignKey("EtapaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_processo_etapa_etapa_etapa_id");

                    b.HasOne("System.Api.Models.Processo", "Processo")
                        .WithMany("Etapas")
                        .HasForeignKey("ProcessoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_processo_etapa_processo_processo_id");

                    b.Navigation("Etapa");

                    b.Navigation("Processo");
                });

            modelBuilder.Entity("System.Api.Models.Quiz", b =>
                {
                    b.HasOne("System.Api.Models.Usuario", "Usuario")
                        .WithMany("Quizzes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_quiz_usuario_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("System.Api.Models.QuizResposta", b =>
                {
                    b.HasOne("System.Api.Models.Quiz", "Quiz")
                        .WithMany("Respostas")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_resposta_quiz_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("System.Api.Models.TokenRedefinicaoSenha", b =>
                {
                    b.HasOne("System.Api.Models.Usuario", "Usuario")
                        .WithMany("TokensRedefinicaoSenha")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_token_redefinicao_senha_usuario_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("System.Api.Models.CondutorAutorizado", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("System.Api.Models.Etapa", b =>
                {
                    b.Navigation("Acoes");

                    b.Navigation("DocumentosExigidos");
                });

            modelBuilder.Entity("System.Api.Models.Processo", b =>
                {
                    b.Navigation("Condutores");

                    b.Navigation("Documentos");

                    b.Navigation("Dossie");

                    b.Navigation("Etapas");
                });

            modelBuilder.Entity("System.Api.Models.Quiz", b =>
                {
                    b.Navigation("Processo");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("System.Api.Models.Usuario", b =>
                {
                    b.Navigation("Conducoes");

                    b.Navigation("Processos");

                    b.Navigation("Quizzes");

                    b.Navigation("TokensRedefinicaoSenha");
                });
#pragma warning restore 612, 618
        }
    }
}
